# https://taskfile.dev
version: '3'

interval: 500ms # default interval for watch tasks is 5s

tasks:
  default:
    desc: Default task; test and coverage
    cmds:
      - task: test
      - task: coverage
    watch: true
    sources:
      - "**/*.go"

  test:
    desc: Run tests
    cmds:
      - go test -v ./...
      - task: coverage
    silent: true

  coverage:
    desc: Generate coverage report and print it to the console
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out

  html-coverage:
    desc: Generate HTML coverage report and open it in the browser
    cmds:
      - task: coverage      
      - go tool cover -html=coverage.out

  build:
    desc: Build the binary
    cmds:
      - go build -o bin/calcweb

  run:
    desc: Run the binary
    cmds:
      - task: build
      - bin/calcweb
